[package]
name = "jsx_macro"
version = "0.1.0"
authors = ["Dragan <dragan.novakovic@bridgewaterlabs.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro-hack = "0.5"
proc-macro2 = "0.4"
quote = "0.6.12"
snax = { version = "0.2.0" }